#!/bin/sh
certtool --generate-privkey --bits 2048 --outfile /etc/ssl/private/server.key 
certtool --generate-self-signed --load-privkey /etc/ssl/private/server.key --outfile /etc/ssl/certs/server.crt
